### ISSUE TITLE
Improve way of implementing blas_sys

### ISSUE THREAD

**Issue by gustav1101** [vab9/pir-project2017#13]
As of now we can work with blas_sys (yay!) but we need to install a c-compiler and gfortran before we do that (boho:( ). So It would be good if someone could work a way around that or at least put the necessary stuff into a script so that installation works automated.

**Comment by jonas-schievink** [comment]
Depending on which features you need for this project, a simpler crate for linear algebra might do the trick. There's a number of crates implemented in pure Rust, so no C compiler is needed: cgmath, nalgebra and rulinalg, to name a few.

**Comment by toschneider** [comment]
Blas seems to be the only crate fast enough for the amount of matrix multiplication we'll have

**Comment by jonas-schievink** [comment]
Please don't waste time prematurely optimizing unwritten and unbenchmarked code. I'm frequently making that mistake, and it costs hours (if not days) of work each time.

If you really have to use BLAS, please consider using the [blas crate](https://crates.io/crates/blas) instead of blas-sys. [blas-sys](https://docs.rs/blas-sys/0.6.6/blas_sys/c/index.html) is only an FFI binding to the C library (CBLAS), which means that all functions use raw pointers and are unsafe - two topics that weren't yet convered in the lecture (AFAIK). `blas` still uses the (apparently) well-known BLAS functions, but exposes a typesafe interface that should be much simpler to use.

**Comment by gustav1101** [comment]
Looks like blas has blas-sys as dependency and probably uses the same unsafe methoda that blas-sys has, but with rust data types and maybe some input sanitising. I'd say let's use that then.

**Comment by vab9** [comment]
Da wir uns ja jetzt anscheinend auf nalgebra geeinigt haben, schliesse ich des hier mal...
