### ISSUE TITLE
serialising the NN state

### ISSUE THREAD

**Issue by toschneider** [vab9/pir-project2017#7]
saves the networks matrix.
- serialisation
- most likely possible with some crate

**Comment by LukasKalbertodt** [comment]
There are two popular crates for serialization:

- `rustc_serialize`: blessed by the compiler in a way, but not really "good"
- `serde`: independent of the compiler, seems to be "good"

The problem is that the `#[derive()]` thingy is very useful for serialization libraries. In `rustc_serialize` you can write `#[derive(RustcEncodable)]` to add certain trait implementations to your type. That way it's super easy to serialize some types into various formats, like JSON.

But this only works because the compiler knows about `rustc_serialize` (it gets a special treatment). For a long time you weren't able to write a "*custom derive*" for yourself when using the stable compiler. Meaning: when you have a trait `Foo` you can't simply annotate `#[derive(Foo)]` on types. This obviously limited the usefulness of external serialization libraries like `serde`.

Luckily, the *custom derive* feature will be working on stable in 7 days (with the release of rust stable 1.15 on the next Friday). So there are basically four possibilities:

1. Use `rustc_serialize` (as mentioned above, it's not the best choice in regards to API design and performance)
2. Wait one week and use `serde`
3. Use `serde` immediately by using `rustc 1.15 beta` for one week. You simply do that with `rustup`, the recommended tool for installing Rust. You can download beta by executing `rustup update beta` and activate it with `rustup default beta`. But remember to switch back to stable again in a week: `rustup default stable`. For more information about rustup, you might want to read [this](https://github.com/rust-lang-nursery/rustup.rs).
4. Serialize by hand (I would not recommend doing that)

**Comment by vab9** [comment]
We want to be able to save several models and select which one to use for a classification on the cl..
relevant issue: #11
